"""Keyword data for Hanoi flood-transport trial crawl.

Transcribed from `Danh mục từ khoá crawl dữ liệu.xlsx`, sheet "Ngập lụt"
(cells B2/B3/B4). Sheet "Xe bus điện" is out of scope (empty, header-only).

Corrections applied against the raw workbook cells:
- B3 cell "grap"/"be" typo split into two separate literal terms, "grap"
  corrected to "grab".
- B4 regex `re:\\\\bHN\\\\b` (double backslash in source) normalized to the
  standard single-backslash word-boundary regex `\\bHN\\b`.
"""

FLOOD_STATE = [
    {"term": r"\bngập\b(?!\s*tràn)", "type": "regex"},
    {"term": "ngập nước", "type": "literal"},
    {"term": "ngập úng", "type": "literal"},
    {"term": "ngập lụt", "type": "literal"},
    {"term": "lụt", "type": "literal"},
    {"term": "đường ngập", "type": "literal"},
    {"term": "phố ngập", "type": "literal"},
    {"term": "mưa ngập", "type": "literal"},
    {"term": "mưa lớn gây ngập", "type": "literal"},
    {"term": "mưa kéo dài", "type": "literal"},
    {"term": "mưa cực đoan", "type": "literal"},
    {"term": "nước dâng", "type": "literal"},
    {"term": "nước tràn", "type": "literal"},
    {"term": "nước ngập", "type": "literal"},
    {"term": "điểm ngập", "type": "literal"},
    {"term": "vùng ngập", "type": "literal"},
    {"term": "ngập cục bộ", "type": "literal"},
    {"term": "ngập sâu", "type": "literal"},
    {"term": "ngập diện rộng", "type": "literal"},
    {"term": "thoát nước không kịp", "type": "literal"},
    {"term": "hệ thống thoát nước", "type": "literal"},
    {"term": "ngập.{0,20}(đường|phố|hầm|cầu)", "type": "regex"},
]

TRANSPORT_IMPACT = [
    {"term": "giao thông", "type": "literal"},
    {"term": "đi", "type": "literal"},
    {"term": "đi lại", "type": "literal"},
    {"term": "di chuyển", "type": "literal"},
    {"term": "lưu thông", "type": "literal"},
    {"term": "tham gia giao thông", "type": "literal"},
    {"term": "người đi đường", "type": "literal"},
    {"term": "người tham gia giao thông", "type": "literal"},
    {"term": "hành trình", "type": "literal"},
    {"term": "chuyến đi", "type": "literal"},
    {"term": "lộ trình", "type": "literal"},
    {"term": "tuyến đường", "type": "literal"},
    {"term": "đường đi", "type": "literal"},
    {"term": "xe máy", "type": "literal"},
    {"term": "xe mô tô", "type": "literal"},
    {"term": "ô tô", "type": "literal"},
    {"term": "xe con", "type": "literal"},
    {"term": "xe đạp", "type": "literal"},
    {"term": "xe điện", "type": "literal"},
    {"term": "xe buýt", "type": "literal"},
    {"term": "xe bus", "type": "literal"},
    {"term": "bus", "type": "literal"},
    {"term": "tuyến buýt", "type": "literal"},
    {"term": "trạm xe buýt", "type": "literal"},
    {"term": "điểm dừng", "type": "literal"},
    {"term": "bến xe", "type": "literal"},
    {"term": "taxi", "type": "literal"},
    {"term": "xe công nghệ", "type": "literal"},
    {"term": "grab", "type": "literal"},
    {"term": "be", "type": "literal"},
    {"term": "đi làm", "type": "literal"},
    {"term": "đi học", "type": "literal"},
    {"term": "đón con", "type": "literal"},
    {"term": "về nhà", "type": "literal"},
    {"term": "ra đường", "type": "literal"},
    {"term": "qua đường", "type": "literal"},
    {"term": "đi qua", "type": "literal"},
    {"term": "vượt qua", "type": "literal"},
    {"term": "lội qua", "type": "literal"},
    {"term": "ùn tắc", "type": "literal"},
    {"term": "tắc đường", "type": "literal"},
    {"term": "kẹt xe", "type": "literal"},
    {"term": "ách tắc", "type": "literal"},
    {"term": "tắc nghẽn", "type": "literal"},
    {"term": "đứng im", "type": "literal"},
    {"term": "chôn chân", "type": "literal"},
    {"term": "xếp hàng dài", "type": "literal"},
    {"term": "dòng xe kéo dài", "type": "literal"},
    {"term": "giao thông hỗn loạn", "type": "literal"},
    {"term": "giao thông tê liệt", "type": "literal"},
    {"term": "gián đoạn giao thông", "type": "literal"},
    {"term": "chia cắt", "type": "literal"},
    {"term": "cấm đường", "type": "literal"},
    {"term": "phong tỏa", "type": "literal"},
    {"term": "đóng đường", "type": "literal"},
    {"term": "không thể lưu thông", "type": "literal"},
    {"term": "không đi qua được", "type": "literal"},
    {"term": "đường không thể đi", "type": "literal"},
    {"term": "tạm dừng hoạt động", "type": "literal"},
    {"term": "tuyến bị gián đoạn", "type": "literal"},
    {"term": "chậm", "type": "literal"},
    {"term": "trễ", "type": "literal"},
    {"term": "muộn", "type": "literal"},
    {"term": "trễ giờ", "type": "literal"},
    {"term": "muộn giờ", "type": "literal"},
    {"term": "đi làm muộn", "type": "literal"},
    {"term": "đi học muộn", "type": "literal"},
    {"term": "chậm chuyến", "type": "literal"},
    {"term": "trễ chuyến", "type": "literal"},
    {"term": "thời gian di chuyển tăng", "type": "literal"},
]

HANOI_LOCATION = [
    {"term": "Hà Nội", "type": "literal"},
    {"term": "Ha Noi", "type": "literal"},
    {"term": "Thủ đô", "type": "literal"},
    {"term": "\\bHN\\b", "type": "regex"},
    {"term": "Hoàn Kiếm", "type": "literal"},
    {"term": "Ba Đình", "type": "literal"},
    {"term": "Đống Đa", "type": "literal"},
    {"term": "Hai Bà Trưng", "type": "literal"},
    {"term": "Cầu Giấy", "type": "literal"},
    {"term": "Thanh Xuân", "type": "literal"},
    {"term": "Hoàng Mai", "type": "literal"},
    {"term": "Hà Đông", "type": "literal"},
    {"term": "Tây Hồ", "type": "literal"},
    {"term": "Long Biên", "type": "literal"},
    {"term": "Nam Từ Liêm", "type": "literal"},
    {"term": "Bắc Từ Liêm", "type": "literal"},
    {"term": "Thanh Trì", "type": "literal"},
    {"term": "Gia Lâm", "type": "literal"},
    {"term": "Đông Anh", "type": "literal"},
    {"term": "Sóc Sơn", "type": "literal"},
    {"term": "Hoài Đức", "type": "literal"},
    {"term": "Đan Phượng", "type": "literal"},
    {"term": "Thường Tín", "type": "literal"},
    {"term": "Thanh Oai", "type": "literal"},
    {"term": "Quốc Oai", "type": "literal"},
    {"term": "Chương Mỹ", "type": "literal"},
    {"term": "Mê Linh", "type": "literal"},
    {"term": "Phúc Thọ", "type": "literal"},
    {"term": "Thạch Thất", "type": "literal"},
    {"term": "Sơn Tây", "type": "literal"},
    {"term": "Ba Vì", "type": "literal"},
    {"term": "Mỹ Đức", "type": "literal"},
    {"term": "Ứng Hòa", "type": "literal"},
    {"term": "Phú Xuyên", "type": "literal"},
    {"term": "Mỹ Đình", "type": "literal"},
    {"term": "Cầu Diễn", "type": "literal"},
    {"term": "Nhổn", "type": "literal"},
    {"term": "Xuân Phương", "type": "literal"},
    {"term": "Tây Mỗ", "type": "literal"},
    {"term": "Đại Mỗ", "type": "literal"},
    {"term": "Trung Văn", "type": "literal"},
    {"term": "Mễ Trì", "type": "literal"},
    {"term": "Yên Hòa", "type": "literal"},
    {"term": "Dịch Vọng", "type": "literal"},
    {"term": "Nghĩa Đô", "type": "literal"},
    {"term": "Kim Giang", "type": "literal"},
    {"term": "Định Công", "type": "literal"},
    {"term": "Linh Đàm", "type": "literal"},
    {"term": "Đại Kim", "type": "literal"},
    {"term": "Yên Sở", "type": "literal"},
    {"term": "Văn Quán", "type": "literal"},
    {"term": "Mỗ Lao", "type": "literal"},
    {"term": "La Khê", "type": "literal"},
    {"term": "Dương Nội", "type": "literal"},
    {"term": "An Khánh", "type": "literal"},
    {"term": "Vinhomes Smart City", "type": "literal"},
    {"term": "Vinhomes Ocean Park", "type": "literal"},
    {"term": "Nguyễn Trãi", "type": "literal"},
    {"term": "Nguyễn Xiển", "type": "literal"},
    {"term": "Khuất Duy Tiến", "type": "literal"},
    {"term": "Nguyễn Tuân", "type": "literal"},
    {"term": "Quan Nhân", "type": "literal"},
    {"term": "Vũ Trọng Phụng", "type": "literal"},
    {"term": "Tố Hữu", "type": "literal"},
    {"term": "Lê Văn Lương", "type": "literal"},
    {"term": "Trần Duy Hưng", "type": "literal"},
    {"term": "Phạm Hùng", "type": "literal"},
    {"term": "Dương Đình Nghệ", "type": "literal"},
    {"term": "Trần Bình", "type": "literal"},
    {"term": "Hồ Tùng Mậu", "type": "literal"},
    {"term": "Cầu Giấy", "type": "literal"},
    {"term": "Xuân Thủy", "type": "literal"},
    {"term": "Phạm Văn Đồng", "type": "literal"},
    {"term": "Hoàng Quốc Việt", "type": "literal"},
    {"term": "Thụy Khuê", "type": "literal"},
    {"term": "Đội Cấn", "type": "literal"},
    {"term": "Minh Khai", "type": "literal"},
    {"term": "Tam Trinh", "type": "literal"},
    {"term": "Lĩnh Nam", "type": "literal"},
    {"term": "Nguyễn Chính", "type": "literal"},
    {"term": "Giải Phóng", "type": "literal"},
    {"term": "Ngọc Hồi", "type": "literal"},
    {"term": "Quang Trung", "type": "literal"},
    {"term": "Yên Nghĩa", "type": "literal"},
    {"term": "Đại lộ Thăng Long", "type": "literal"},
    {"term": "Pháp Vân", "type": "literal"},
    {"term": "Cầu Bươu", "type": "literal"},
]

GROUPS = {
    "flood_state": FLOOD_STATE,
    "transport_impact": TRANSPORT_IMPACT,
    "hanoi_location": HANOI_LOCATION,
}


def literal_terms(group_name, groups=GROUPS):
    """Order-preserving dedup of literal terms; regex entries excluded (search input only)."""
    seen, out = set(), []
    for entry in groups[group_name]:
        if entry["type"] != "literal":
            continue
        key = entry["term"].strip().lower()
        if key and key not in seen:
            seen.add(key)
            out.append(entry["term"].strip())
    return out
